name: Web CI

on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Install Yarn
        run: npm install -g yarn

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: yarn install

      - name: Run Jest tests with coverage
        run: yarn test:coverage

  e2e:
    runs-on: ubuntu-20.04
    container: lironavon/docker-puppeteer-container:14.16.0
    steps:
      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@v4
        with:
          node-version: lts/*

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: yarn install

      - name: Run e2e tests
        run: yarn test
