name: Web CI

on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Install Yarn
        run: npm install -g yarn

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Jest tests
        run: yarn test:unit -- --watchAll=false

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Install Yarn
        run: npm install -g yarn

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Jest tests
        run: yarn test:local -- --watchAll=false
