name: Web CI

on: push

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Install Yarn
        run: npm install -g yarn

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Jest tests
        run: yarn test:unit -- --watchAll=false

  e2e:
    runs-on: ubuntu-20.04
    container: lironavon/docker-puppeteer-container:14.16.0
    steps:
      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@v4
        with:
          node-version: lts/*

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run e2e tests
        run: yarn test

      # - name: Check Cypress tests exist
      #   id: check_cypress_tests
      #   uses: andstor/file-existence-action@v1
      #   with:
      #     files: "cypress/integration/"

      # - name: Install and run Cypress tests
      #   uses: cypress-io/github-action@v2
      #   if: steps.check_cypress_tests.outputs.files_exists == 'true'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     build: npm run build --if-present
      #     start: npm start
      #     wait-on: "http://localhost:3000"
